### ISSUE TITLE
Where can I find API documentation?

### ISSUE THREAD

**Issue by jhunahn** [VKCOM/devicehub#18]
**What is the issue or idea you have?**

I operate a devicefarmer at my company, and I created and use a cli-tool called device-farmer-client.
This is a tool that acquires devices and runs test scripts using devicefarmer's RestAPI.

In `devicefarmer/stf`, I could to check the API via swagger-io. But, it seems that devicehub does not support swagger.

```bash
$ curl http://localhost:8082/api/v1/swagger.json
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/swagger.json</pre>
</body>
</html>
```

With devicehub, can I no longer test my APIs using Swagger? Where can I find API documentation?

**Comment by irdkwmnsb** [comment]
We have turned off the swagger api route, but you can read it as a file from https://github.com/VKCOM/devicehub/blob/master/lib/units/api/swagger/api_v1.yaml

Do you need it as an http accessible api route?

Also, there is a ready to use python library that you can vendor in your project:
https://github.com/VKCOM/devicehub/tree/master/test/api/smartphone-test-farm-client

**Comment by DaniilSmirnov** [comment]
I think we need to fix swagger route. I'll create task for next sprint in internal tracker

**Comment by jhunahn** [comment]
@DaniilSmirnov Thank you for consider it.

@irdkwmnsb [smartphone-test-farm-client](https://github.com/VKCOM/devicehub/tree/master/test/api/smartphone-test-farm-client) is really great!
I will try to develop a tester that combines this with adbutil. thank you.

**Comment by irdkwmnsb** [comment]
Internal tracker id: QA-15376
