### ISSUE TITLE
Issue with first run\install

### ISSUE THREAD

**Issue by candy69** [VKCOM/devicehub#51]
After running "docker compose -f docker-compose-prod.yaml --env-file scripts/variables.env up"

getting error:

ERROR: for devicehub-migrate  Container "779e83aeff9b" exited with code 132.

**Comment by irdkwmnsb** [comment]
Hi! What commit are you trying this from?

**Comment by candy69** [comment]
> Hi! What commit are you trying this from?

Hi, thank you for reply. I'm trying to run it from main commit, cloned it and tried to run from app directory.
